"""
backend/features/feature_04/models.py
======================================
ZeroKnow KYC — SQLAlchemy ORM model for ZK proof records.

STRICT RULES followed:
- Uses its OWN DeclarativeBase import (not from db.database) so this model
  is fully self-contained and does not pollute the existing table registry.
- Alembic migration for this table lives in:
    backend/db/migrations/versions/004_zk_kyc.py  (see CHANGES.md)
- The actual Rider ID is NEVER stored here — only the hash and nullifier.

Table: zk_proofs
"""

from sqlalchemy import Column, String, DateTime, Text, Boolean, Index
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.sql import func


class ZKBase(DeclarativeBase):
    """
    Isolated declarative base for Feature 04 ZK tables.

    Separate from db.database.Base intentionally: this prevents the ZK table
    from being accidentally picked up by other features' metadata scans and
    keeps the feature self-contained.
    """
    pass


class ZKProof(ZKBase):
    """
    Stores the result of a successful ZK proof verification.

    What IS stored:
        riderIDHash    — Poseidon hash of the Rider ID field element (hex)
        nullifier      — Poseidon(riderIDField, salt) — deduplication token (hex)
        proofTimestamp — UTC datetime when the proof was verified server-side

    What is NOT stored:
        ❌ Rider ID (plain-text)
        ❌ riderIDField (encoded integer)
        ❌ salt
        ❌ The proof itself (π_A, π_B, π_C) — proofs are ephemeral and large;
           re-verification can be done by the client generating a new proof.

    Indexes:
        - nullifier has a UNIQUE index — prevents duplicate submissions.
        - rider_id_hash has a non-unique index for lookup by commitment.
    """

    __tablename__ = "zk_proofs"

    # Primary key: UUID generated by the server at verification time
    id = Column(String(36), primary_key=True)

    # Poseidon hash of the encoded Rider ID — hex string (0x-prefixed, 66 chars)
    # Used by the onboarding flow to link a ZK proof to a rider account
    # without ever touching the actual Rider ID.
    rider_id_hash = Column(String(68), nullable=False)

    # Deduplication nullifier — UNIQUE constraint enforced here + DB index.
    # If the same identity tries to submit a second proof, the nullifier
    # will collide and the request is rejected with 409 Conflict.
    nullifier = Column(String(68), nullable=False)

    # Circuit public signals stored as raw JSON for auditability.
    # Format: JSON array ["riderIDHash", "nullifier", "minEntropy"]
    # This lets the verifier re-run the verification if needed.
    public_signals_json = Column(Text, nullable=True)

    # ISO-8601 UTC timestamp of server-side verification
    proof_timestamp = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    # Whether this proof has been consumed by the onboarding flow.
    # Prevents a valid proof from being used to onboard multiple accounts.
    consumed = Column(Boolean, nullable=False, default=False)

    # Soft-delete / revocation: set to True if the proof is revoked
    # (e.g. the associated rider account is suspended).
    revoked = Column(Boolean, nullable=False, default=False)

    # Metadata
    created_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    # -----------------------------------------------------------------------
    # Table-level constraints and indexes
    # -----------------------------------------------------------------------
    __table_args__ = (
        # Unique nullifier: the primary deduplication mechanism.
        Index("ix_zk_proofs_nullifier", "nullifier", unique=True),
        # Non-unique lookup by riderIDHash (one rider may theoretically
        # re-verify, though consumed=True prevents double-onboarding).
        Index("ix_zk_proofs_rider_id_hash", "rider_id_hash"),
    )

    def __repr__(self) -> str:
        return (
            f"<ZKProof id={self.id!r} "
            f"rider_id_hash={self.rider_id_hash[:12]!r}... "
            f"nullifier={self.nullifier[:12]!r}... "
            f"consumed={self.consumed}>"
        )
